export const data = [
  {
    id: 1,
    name: 'Офицер полиции',
    description: 'Офицер полиции - это человек, который работает в полиции. Он следит за порядком в городе и защищает людей от преступников.',
    image: 'https://cdn.create.vista.com/api/media/medium/430145802/stock-photo-police-officer-sunglasses-standing-crossed?token=',
    salary_start: 200000,
    salary_end: 300000,
    education: 'Высшее',
    experience: 'Не требуется',
    requirements: 'Наличие паспорта, наличие прав категории B',
    duties: 'Следить за порядком в городе, защищать людей от преступников',
    conditions: 'Офицер полиции работает в полиции',
    contacts: 'Телефон: 8-800-555-35-35',
    address: 'г. Москва, ул. Пушкина, д. Колотушкина',
    schedule: 'Полный рабочий день',
    type: 'Полная занятость',
    category: 'Охрана, безопасность',
    company: 'МВД',
    city: 'Павлодар',
    date: '2020-11-08',
  },
  {
    id: 2,
    name: 'Инспектор ГИБДД',
    description: 'Инспектор ГИБДД - это человек, который работает в ГИБДД. Он следит за порядком на дорогах и защищает людей от нарушителей правил дорожного движения.',
    image: 'https://www.rudorogi.ru/content/upload/image/pdd-2/traffic_police_inspector_stops_car.jpeg',
    salary_start: 200000,
    salary_end: 300000,
    education: 'Высшее',
    experience: 'Не требуется',
    requirements: 'Наличие паспорта, наличие прав категории B',
    duties: 'Следить за порядком на дорогах, защищать людей от нарушителей правил дорожного движения',
    conditions: 'Инспектор ГИБДД работает в ГИБДД',
    contacts: 'Телефон: 8-800-555-35-35',
    address: 'г. Москва, ул. Пушкина, д. Колотушкина',
    schedule: 'Полный рабочий день',
    type: 'Полная занятость',
    category: 'Охрана, безопасность',
    company: 'МВД',
    city: 'Павлодар',
    date: '2020-11-08',
  },
]
